rstcheck.py

Hello,
I added the directive and the role from Sphinx domains. It will be more universal way.

Add directive and role from Sphinx domains

---

rstcheck.py

Hello,
I had a problem to ask rstchecker my custom roles and directives. I found a very useful way to do this. Rstchecker just takes a configuration file from the directory in which you run it. For example:
I have the following file structure.
```
docs
├── foo
│   └── bar.rst
├── index.rst
└── .rstcheck.ini
```
``.rstcheck.ini`` contains:
```
[roles]
ignore=src
[directives]
ignore=one,two,tree
```
``bar.rst`` contains:
```
Bar
===
:src:`hello_world.py`
```
Ok. If I run ``rstcheck foo/bar.rst`` from current directory ``docs`` then errors will not. But, If I run ``rstcheck bar.rst`` from current directory ``docs/foo`` you will get an error.
In the first case, applied settings from a file.

Experiment with the local config file

---

README.rst

add config docs

---

.travis.yml
Makefile
README.rst
rstcheck.py
setup.py
test_rstcheck.py

Make Sphinx optional

---

Makefile
examples/good/bom.rst
rstcheck.py

Remove BOM to avoid false positives from docutils

---

.travis.yml

Add Python 3.6 and nightly, and PyPy 5.4.

.travis.yml: Add more Python versions

---

.travis.yml
README.rst

(I'm also trying to debug Travis CI.)

Document tests

---

rstcheck.py

Added possibility to write configuration to a setup.cfg file
Ordered imports in rstcheck.py
Deleted useless blank line in test_rstcheck.py
Closes #37

Allow configuration to be in `setup.cfg`

---

README.rst
rstcheck.py
test.bash

Add `--recursive` option

---

rstcheck.py

Full support for configuration file

---

README.rst
examples/with_configuration/.rstcheck.cfg
examples/with_configuration/bad.rst
examples/with_configuration/good.rst
rstcheck.py
test.bash

Configuration file - part 2

---

.travis.yml
rstcheck.py

Fix compatibility with sphinx>=1.8

---

README.rst
examples/with_configuration/dummydir/readme.txt
examples/with_configuration/rstcheck.ini
examples/without_configuration/good.rst
rstcheck.py
test.bash

This addresses https://github.com/myint/rstcheck/issues/56
This is a tentative implementation of my proposed solution of adding a `--config` option, open to discussion. This pull request is not yet ready to be merged; at the very least, it would need additional documentation and tests.

Add --config option

---

.pre-commit-hooks.yaml
README.rst

Added pre-commit-hooks.yaml to enable inclusion as a pre-commit hook for https://pre-commit.com/

Add pre-commit execution option

---

rstcheck/__init__.py

Basically what https://github.com/psf/black/pull/838 did.
Fixes #85

Limit the pool size on Windows

---

README.rst

Document renamed CLI option --report to --report-level

---

README.rst
src/rstcheck/_sphinx.py
src/rstcheck/runner.py
tests/test__sphinx.py

only register sphinx nodes once; fixes #113

---

.pre-commit-config.yaml
README.rst
pyproject.toml
src/rstcheck/__init__.py
src/rstcheck/_docutils.py
src/rstcheck/_extras.py
src/rstcheck/_sphinx.py
src/rstcheck/checker.py
src/rstcheck/cli.py
src/rstcheck/config.py
src/rstcheck/inline_config.py
src/rstcheck/runner.py
tests/test_checker.py
tests/test_cli.py
tests/test_config.py
tests/test_inline_config.py

Resolves: #99 
With the restructure in #100 the `--debug` flag was removed. With this PR the logging module is implemented to bring a better logging experience with more logging levels.

Add logging

---

README.rst
src/rstcheck/cli.py
src/rstcheck/config.py
src/rstcheck/runner.py
testing/examples/with_configuration/bad_config.cfg
testing/examples/with_configuration/bad_config.toml
tests/integration_tests/test_cli.py
tests/test_config.py
tests/test_runner.py

Feat 115 warn unsupported settings

---

.github/workflows/documentation.yaml
CHANGELOG.md
docs/source/spelling_dict.txt
docs/source/usage/config.rst

Improve config docu

---

CHANGELOG.md
docs/source/usage/integration.rst

update megalinter urls

---

.gitignore
CHANGELOG.md
docs/source/installation.rst

The GitHub URL in the installation instructions pointed to your fork rather than the "official" repository.  I presume the official repository URL is more appropriate.

docs: update GitHub URL in installation instructions

---

CHANGELOG.md
docs/source/faq.rst
docs/source/spelling_dict.txt
pyproject.toml

Fix typer click version incompatiblity

---

CHANGELOG.md
pyproject.toml

Drop py 37

---

.github/workflows/documentation.yml
.github/workflows/qa.yml
.github/workflows/test.yml
.github/workflows/update-authors.yaml
.gitignore
.pre-commit-config.yaml
CHANGELOG.md
MANIFEST.in
docs/source/conf.py
docs/source/workflows/development.rst
docs/source/workflows/releases.rst
poetry.toml
pyproject.toml
src/rstcheck/_compat.py
tox.ini

update project like https://github.com/rstcheck/rstcheck-core/pull/59

switch from poetry to setuptools

---

CHANGELOG.md
pyproject.toml
tox.ini

Drop sphinx 4 support

---

CHANGELOG.md
tox.ini

add sphinx 8 to tox test envs
